//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDatVe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public int MaChiTietDonHang { get; set; }
        public int MaDonHang { get; set; }
        public int MaGhe { get; set; }
        public int MaXuatChieu { get; set; }
        public Nullable<int> GiaVe { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual Ghe Ghe { get; set; }
        public virtual XuatChieu XuatChieu { get; set; }
    }
}
