//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDatVe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHangDichVu
    {
        public int MaDonHangDichVu { get; set; }
        public int MaDonHang { get; set; }
        public int MaDichVu { get; set; }
        public int SoLuong { get; set; }
        public int DonGia { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual DonHang DonHang { get; set; }
    }
}
