//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDatVe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichChieu
    {
        public LichChieu()
        {
            this.XuatChieux = new HashSet<XuatChieu>();
        }
    
        public int MaLichChieu { get; set; }
        public int MaRap { get; set; }
        public int MaPhim { get; set; }
        public System.DateTime NgayChieu { get; set; }
    
        public virtual Phim Phim { get; set; }
        public virtual Rap Rap { get; set; }
        public virtual ICollection<XuatChieu> XuatChieux { get; set; }
    }
}
