//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDatVe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebDatVePhimEntities : DbContext
    {
        public WebDatVePhimEntities()
            : base("name=WebDatVePhimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public DbSet<DichVu> DichVus { get; set; }
        public DbSet<DonHang> DonHangs { get; set; }
        public DbSet<DonHangDichVu> DonHangDichVus { get; set; }
        public DbSet<Ghe> Ghes { get; set; }
        public DbSet<KhachHang> KhachHangs { get; set; }
        public DbSet<LichChieu> LichChieux { get; set; }
        public DbSet<PhanQuyen> PhanQuyens { get; set; }
        public DbSet<Phim> Phims { get; set; }
        public DbSet<Phong> Phongs { get; set; }
        public DbSet<Rap> Raps { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TaiKhoan> TaiKhoans { get; set; }
        public DbSet<TheLoai> TheLoais { get; set; }
        public DbSet<TinTuc> TinTucs { get; set; }
        public DbSet<XuatChieu> XuatChieux { get; set; }
    }
}
