//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDatVe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        public Phong()
        {
            this.Ghes = new HashSet<Ghe>();
            this.XuatChieux = new HashSet<XuatChieu>();
        }
    
        public int MaPhong { get; set; }
        public int MaRap { get; set; }
        public string TenPhong { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<Ghe> Ghes { get; set; }
        public virtual Rap Rap { get; set; }
        public virtual ICollection<XuatChieu> XuatChieux { get; set; }
    }
}
