//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDatVe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XuatChieu
    {
        public XuatChieu()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }
    
        public int MaXuatChieu { get; set; }
        public int MaLichChieu { get; set; }
        public int MaPhong { get; set; }
        public int GioChieu { get; set; }
        public int PhutChieu { get; set; }
        public int LoaiChieuPhim { get; set; }
    
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual LichChieu LichChieu { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
